# Generated by Django 3.0.5 on 2020-04-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='body',
            new_name='illness',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='posts',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
